spring.application.name=ews-system
spring.datasource.url = jdbc:mysql://kodama.proxy.rlwy.net:36445/railway
spring.datasource.username = root
spring.datasource.password = STrEAEAcNfmfezQwpraQwDlefAzDQtKb
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true